### ISSUE TITLE
Sorry that I have to contact you like this - ms-teams-green-status-defender

### ISSUE THREAD

**Issue by oc-tk** [eric19960304/hello-world-overengineering#1]
So yea, I was big fun of ms-teams-green-status-defender, is there a chance for copy for private usage?

**Comment by eric19960304** [comment]
Hi, I didn't know someone is using my toy website.
Recently my Github pro account was expired so all my Github Pages were gone.
I just moved it to my personal potato server: https://teams-defender.coder.faith/
Enjoy.

**Comment by oc-tk** [comment]
Thanks man, I tested different tools and your was working the best for me. I have found it by google with simple search. Really thanks

**Comment by oc-tk** [comment]
server is down? could you maybe create seperate project for this? I am interested in implementation

**Comment by eric19960304** [comment]
I just moved it to Github page again, see https://github.com/eric19960304/ms-teams-status-defender
